image: alpine:3.6

variables:
    REGISTRY_URL: "docker.marvin-menzerath.de"
    PROJECT_GROUP: "marvin"
    PROJECT_NAME: "putr"

build_master:
    image: docker:latest
    stage: build
    services:
        - docker:dind
    only:
        - master
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_URL
        - docker build -t $REGISTRY_URL/$PROJECT_GROUP/$PROJECT_NAME .
        - docker push $REGISTRY_URL/$PROJECT_GROUP/$PROJECT_NAME

build_develop:
    image: docker:latest
    stage: build
    services:
        - docker:dind
    only:
        - develop
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_URL
        - docker build -t $REGISTRY_URL/$PROJECT_GROUP/$PROJECT_NAME .
        - docker push $REGISTRY_URL/$PROJECT_GROUP/$PROJECT_NAME:develop

build_tag:
    image: docker:latest
    stage: build
    services:
        - docker:dind
    only:
        - tags
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_URL
        - docker build -t $REGISTRY_URL/$PROJECT_GROUP/$PROJECT_NAME .
        - docker push $REGISTRY_URL/$PROJECT_GROUP/$PROJECT_NAME:$CI_COMMIT_TAG
